version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: